### ISSUE TITLE
Extend configuration with `testsCategories` parameter

### ISSUE THREAD

**Issue by AlexPykavy** [jenkins-infra/pipeline-library#186]
Hello,

As far as I see, the current implementation of `buildPlugin` supports defining multiple configurations of environments where build will happen. For example, let's consider `Jenkinsfile` from [docker-workflow-plugin](https://github.com/jenkinsci/docker-workflow-plugin/blob/master/Jenkinsfile) plugin:
```
buildPlugin(platforms: [
    'linux',
    'maven-windows'
])

```

Also, I've noticed that the build will be run in a parallel mode where each branch is executed in its separate environment. And seems like the above code can be rewritten in another form:
```
buildPlugin(configurations: [
    [ platform: 'linux' ],
    [ platform: ''maven-windows' ]
])
```

And, in my opinion, it will super helpful if we can extend this definition with `testsCategories` parameter or something similar, for instance:
```
buildPlugin(configurations: [
    [ platform: 'linux', testsCategories: 'Linux' ],
    [ platform: 'maven-windows', testsCategories: 'Windows' ]
])
```

What do you think about such an idea? Maybe you already have something similar in your backlog, so just share the link to the corresponding issue.

**Comment by jglick** [comment]
I do not see any need for that. A specific test which can only run on certain platforms can detect that at runtime and use `org.junit.Assume` to skip itself if appropriate. We do this all the time, and not just for OS but for presence of tools like Docker, etc.
