### ISSUE TITLE
Pipeline succeeds with failure during incremental upload

### ISSUE THREAD

**Issue by justusbunsi** [jenkins-infra/pipeline-library#250]
Hi. When publishing to https://incrementals.jenkins.io/ it sometimes happen that the artifact couldn't be uploaded for any reason. The pipeline build then does not fail or at least become unstable.

Unfortunately, I haven't noticed that in the Gitea plugin for [my PR](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fgitea-plugin/detail/PR-42/1/pipeline/119) and it got merged. Now the main branch cannot upload the incremental build either.

Is there any reason to have the valid response codes including non 2xx codes?

https://github.com/jenkins-infra/pipeline-library/blob/18bf46ddba7e491403f013aa3baca893832053ea/vars/infra.groovy#L322

**Comment by timja** [comment]
It’s currently set like that intentionally so an issue with the incrementals service doesn’t cause failures with the build

**Comment by justusbunsi** [comment]
Ah. I understand. Thanks for the quick response. So I better add the "incrementals" status check as required for PR builds to prevent such things in the future. 🙂
