### ISSUE TITLE
Feature Request(buildand publichDocker) allow testing images of PRs in the `jenkins4eval` namespace

### ISSUE THREAD

**Issue by dduportal** [jenkins-infra/pipeline-library#279]
If you have a PR like https://github.com/jenkins-infra/docker-builder/pull/34, you would want to test the image before merging/releasing.

@halkeye suggested on IRC that `jenkins4eval/` could be used for that.

This issues is about updating the library so that the deployment stage is run even on PRs, at least on infra.ci, by pushing the image to jenkins4eval/jenkinsciinfra-<image name>:<PR ID>

**Comment by halkeye** [comment]
I'm really likeing preview envs :)

Btw, I *think* its just related to https://github.com/jenkins-infra/pipeline-library/blob/a6261f941d974857a57929c5074955e741e2ba38/src/io/jenkins/infra/InfraConfig.groovy#L22-L28 at least it was when I first wrote the build docker shared lib.

**Comment by dduportal** [comment]
Don't forget that credentials for jenkins4infra might or might not be present as well :) (not sur if we can check this in a pipeline lib)

**Comment by lemeurherve** [comment]
Closed by https://github.com/jenkins-infra/pipeline-library/pull/459/
