### ISSUE TITLE
tune the number of forks run for surefire

### ISSUE THREAD

**Issue by jtnord** [jenkins-infra/pipeline-library#285]
the CI nodes may (or may not have a large number of CPUs), and by default we only run one surefire fork for all tests.

This could be a bit wasteful for many plugins where multiple tests run in parallel could hugely decrease the plugins build time.
(e.g. https://github.com/jenkinsci/git-plugin/pull/1173#discussion_r785025999) 

therefore the number of forks should be tuned for all plugins to a reasonable default (we already tune the surefire JVM args to a set JVM heap so this number could reasonably be caclulated knowing the underlying hardware).

Additionally this tuning may not work for all plugins (for example warnings ng or plugins using `RealJenkinsRule` that require more memory, so allowing this number to be tweaked / overriddien would be required at the same time (or the number chosen would have to be low enough to account for these plguins which could be deemed as wastefull).

Quicker builds on the same hardware will also reduce the number of agents we require which should reduce the cloud costs for the product.

**Comment by dduportal** [comment]
Do you think that this value could be defined based on the amount of vCPUs availables?
