### ISSUE TITLE
Plugin does not build on Jenkins

### ISSUE THREAD

**Issue by vogtmh** [jenkins-infra/pipeline-library#290]
I added your sources to my repo, created a multibranch pipeline on Jenkins and ran it. Unfortunately, I get a some test errors and I don't know how to resolve them. 

Is there any guide on how to create your plugin or maybe just a link to the hpi file? As far as I could see, it's not available via the plugin center of Jenkins. Actually, I need this plugin only to build another plugin.

This is the error message on Jenkins 2.319.2 (latest LTS):
[ERROR] Failures: 
[ERROR]   BuildPluginStepTests.test_getConfigurations_implicit_with_jdkVersions:102 expected:<[null, null, null, null]> but was:<4>
[ERROR]   BuildPluginStepTests.test_getConfigurations_implicit_with_jenkinsVersions:91 expected:<[null, null, null, null]> but was:<4>
[ERROR]   BuildPluginStepTests.test_getConfigurations_implicit_with_platforms:80 expected:<[null, null]> but was:<2>
[INFO] 
[ERROR] Tests run: 89, Failures: 3, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:03 min
[INFO] Finished at: 2022-01-18T22:19:35Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project pipeline-library: There are test failures.

**Comment by vogtmh** [comment]
[jenkins.log](https://github.com/jenkins-infra/pipeline-library/files/7892785/jenkins.log)

**Comment by MarkEWaite** [comment]
> Is there any guide on how to create your plugin or maybe just a link to the hpi file? As far as I could see, it's not available via the plugin center of Jenkins. 

This isn't a plugin.  This is a [Pipeline shared library](https://www.jenkins.io/doc/book/pipeline/shared-libraries/).

Darin Pope provides a tutorial on PIpeline shared libraries at https://www.youtube.com/watch?v=Wj-weFEsTb0

> Actually, I need this plugin only to build another plugin.

You can probably build the other plugin by running the command `mvn clean verify` with Apache Maven 3.8.4.  This Pipeline shared library is a great convenience for plugin maintainers because it automatically builds and tests on Windows and Linux with Java 8 and Java 11.  If you need that level of test coverage, then buildPlugin is a good choice.  If you want to build a plugin so that you can use it, try `mvn clean verify`.

**Comment by MarkEWaite** [comment]
Not a Pipeline shared library issue.  Closing

**Comment by vogtmh** [comment]
I actually want to test out some changes on publish-over-ssh, which is using your library in some way, but I cannot figure out how it works as it's not loading your code before using it. 

I already tried mvn clean verify, which failes with a couple of errors that I'm unable to fix. There is no other plugin providing the same functionality, so I need to find a way to build it properly and I thought your library might be the right way to go.

**Comment by vogtmh** [comment]
https://github.com/jenkinsci/publish-over-ssh-plugin/blob/master/Jenkinsfile

**Comment by MarkEWaite** [comment]
The Pipeline shared library is loaded by an implicit load that is defined in the multibranch Pipeline.  See https://www.youtube.com/watch?v=Wj-weFEsTb0&t=292s for a video description of that technique.  See the [docs](https://www.jenkins.io/doc/book/pipeline/shared-libraries/#using-libraries ) for a written description.

**Comment by vogtmh** [comment]
Hmm.. is this some exclusive functionality of Jenkins Enterprise version? Or do I need to install an extra plugin to get the "Global Pipeline Libraries" section on the Open Source Jenkins?

**Comment by MarkEWaite** [comment]
> Do I need to install an extra plugin to get the "Global Pipeline Libraries" section on the Open Source Jenkins?

Yes, Pipeline shared libraries require the ["Pipeline: Shared Groovy Libraries" plugin](https://plugins.jenkins.io/workflow-cps-global-lib/)
