### ISSUE TITLE
`buildDockerAndPublishImage` fails at `GitHub Release` stage if there are more than one "next" draft releases

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/pipeline-library#379]
https://github.com/jenkins-infra/pipeline-library/blob/8b9941bd72130ea732cc804726218d64da7da22b/vars/buildDockerAndPublishImage.groovy#L199

Example of [failing build](https://infra.ci.jenkins.io/blue/organizations/jenkins/docker-jobs%2Fdocker-openvpn/detail/1.0.75/1/pipeline/113) :
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/91831478/168426157-944416d1-062b-4e7e-9308-fd6ef412308f.png">

<details>
<summary>Corresponding releases</summary>

![image](https://user-images.githubusercontent.com/91831478/168426201-64185b6b-a4d6-4ce8-94b5-17dff10235d4.png)

</details>

https://github.com/jenkins-infra/docker-openvpn/releases

**Comment by dduportal** [comment]
Side note : there is also the case of no « next » release. Usually, adding trigger event « release » on the gh workflow for release drafter fix it. But maybe we could trigger release-drafter here and manage the draft release for ourselves ?
