### ISSUE TITLE
Allow to add a `skip-updatecli` label on pull requests to avoid failing builds when introducing new files

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/pipeline-library#568]

**Comment by dduportal** [comment]
🤔 It's not clear what is the goal? Why would you want to add a new updatecli manifest file if you don't want to check that it work by running it?

(besides, why on pipeline-library?)

**Comment by lemeurherve** [comment]
> it's only the "updatecli" stage that is failing.

Indeed, but looking at the PR on GitHub it's failed:
<img width="589" alt="image" src="https://user-images.githubusercontent.com/91831478/214373604-11f7e4ff-8e6e-4b02-8696-5c3aba3b070e.png">

I know it's not that important (for us with our permissions at least), but I think it could be nice to have and harmless nevertheless.

**Comment by dduportal** [comment]
> > it's only the "updatecli" stage that is failing.
> 
> Indeed, but looking at the PR on GitHub it's failed: <img alt="image" width="589" src="https://user-images.githubusercontent.com/91831478/214373604-11f7e4ff-8e6e-4b02-8696-5c3aba3b070e.png">
> 
> I know it's not that important (for us with our permissions at least), but I think it could be nice to have and harmless nevertheless.

I prefer explicit errors to have a "mark" saying "this PR did not meet the expected behavior" (which updatecli is).
