### ISSUE TITLE
eslint errors fail the maven call for core build

### ISSUE THREAD

**Issue by mawinter69** [jenkins-infra/pipeline-library#874]
### Reproduction steps

1. Create an error in  a javascript file of core
2. create PR

### Expected Results

I'm able to see the eslint problems in the UI at https://ci.jenkins.io/job/Core/job/jenkins/PR-number

### Actual Results

the build fails that prevents the recording of issues

### Anything else?

the build calls yarn lint:ci, this prevents that eslint errors in javascript files are printed to the console. So in order to find the error I need to run a local build where I modify the build to call lint only which prints the errors to the console

**Comment by basil** [comment]
Duplicates [JENKINS-71021](https://issues.jenkins.io/browse/JENKINS-71021).
